[build]
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure JSON files are served correctly
[[headers]]
  for = "/data/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"